# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: balkanultra

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  django:
    build:
      context: .
      dockerfile: docker/local.Dockerfile
    command: sh /entrypoint.sh python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/balkan-app
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: on-failure