# Generated by Django 3.2.25 on 2025-04-02 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_result_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='gender',
            field=models.CharField(default='M', max_length=25),
        ),
        migrations.AddField(
            model_name='athlete',
            name='nationality',
            field=models.CharField(default='BG', max_length=20),
        ),
    ]
