# Generated by Django 3.2.25 on 2025-04-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20250402_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='athlete',
            name='name',
        ),
        migrations.AddField(
            model_name='athlete',
            name='first_name',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='athlete',
            name='last_name',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
        ),
    ]
