# Generated by Django 3.2.25 on 2025-04-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_result_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='nickname',
            field=models.CharField(blank=True, default='', help_text='Standardized name for grouping athletes who wrote their name differently through the years', max_length=25, null=True),
        ),
    ]
