# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: balkanultra
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: balkanultra

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  django:
    build:
      context: .
      dockerfile: ../docker/prod.Dockerfile
    command: sh /entrypoint.sh
    volumes:
      - ..:/balkan-app
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: on-failure